title:  Erstes Internationales Shanti Forum 2020
email:             your-email@example.com
description: Was anfang vom Jahr 2019 als Vision begann, wird nun real umgesetzt in ein breitgefächertes Spektrum von Themen und Referenten die Tätig sind in ganz  verschiedenen Lebensbereichen.
ddd:

author: Shanti

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - README.md

# Social Profiles
twitter_username:
github_username:
facebook_username:
