# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: 1. Internationales Shanti-Forum 2020
email: info@shanti-yoga.ch
url: https://shanti-forum.eu
#baseurl: /shanti-forum
description: >- # this means to ignore newlines until "baseurl:"
 Weltweit ist ein nicht übersehbarer Wandel im Gange, sowohl im individuell menschlichen wie auch in vielen wirtschaftlichen Bereichen. Wachstum stößt an ihre Grenzen! Jedoch gibt es auch sehr viele Bemühungen von Menschen und Institutionen, die im aufbauenden und schützenden Tätig sind für die Erde, den Menschen- Tier- und Pflanzenwelt. <br>An diesem 1. Internationalen Shanti-Forum kommen Menschen zu Wort und stellen Ihre ganz persönliche Zukunftsvision vor - die sie bereits leben, oder am Aufbauen und Weiterentwickeln sind.
locale: de-DE

twitter_username:
github_username:
minimal_mistakes_skin: aqua
search: false

# Build settings
markdown: kramdown
#remote_theme: mmistakes/minimal-mistakes
theme: minimal-mistakes-jekyll
# Outputting
permalink: /:categories/:title/
#paginate: 5 # amount of posts to show
#paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
#  - jekyll-paginate
  - jekyll-sitemap
#  - jekyll-gist
#  - jemoji
  - jekyll-include-cache

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
      read_time: false
      comments: false
      share: false
      related: false
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: false

analytics:
  provider: "google-gtag"
  google:
    tracking_id: "UA-167091919-1"
    anonymize_ip: false # default

compress_html:
  clippings: all
